# Generated by Django 3.1.7 on 2021-06-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencechoice',
            name='answer',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sciencequestion',
            name='attempted_answer_a',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='sciencequestion',
            name='attempted_answer_b',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='sciencequestion',
            name='attempted_answer_c',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='sciencequestion',
            name='correct_answer_a',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='sciencequestion',
            name='correct_answer_b',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='sciencequestion',
            name='correct_answer_c',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='sciencequestion',
            name='question_model',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='sciencequestion',
            name='question_model_index',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sciencequestion',
            name='result_text',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='sciencechoice',
            name='choice_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sciencequestion',
            name='question_text',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
