# Generated by Django 3.1.7 on 2021-06-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0003_auto_20210623_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencequestion',
            name='image_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
