# Generated by Django 3.1.7 on 2021-06-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0006_auto_20210623_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciencequestion',
            name='subtopic_number',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='sciencequestion',
            name='topic_number',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
