# Generated by Django 3.1.7 on 2021-06-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0008_auto_20210623_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencequestion',
            name='question_source',
            field=models.CharField(default='', max_length=100),
        ),
    ]
