# Generated by Django 3.1.7 on 2021-06-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0009_sciencequestion_question_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencequestion',
            name='lv3_topic_number',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
