# Generated by Django 3.1.7 on 2021-06-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0011_sciencequestion_success_on_first_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencequestion',
            name='last_attempt_date',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='sciencequestion',
            name='question_model_index',
            field=models.CharField(default='000', max_length=200),
        ),
    ]
