# Generated by Django 3.1.7 on 2021-06-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0012_auto_20210626_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_index', models.CharField(default='0', max_length=10)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('number_of_success_first_attempt', models.IntegerField(default=0)),
                ('number_of_latest_success_attempt', models.IntegerField(default=0)),
                ('question_model', models.CharField(default='NA', max_length=2000)),
                ('question_text', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
