# Generated by Django 3.1.7 on 2021-06-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0013_sciencetopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceLevel3Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_index', models.CharField(default='0', max_length=10)),
                ('topic_name', models.CharField(default='0', max_length=500)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('number_of_success_first_attempt', models.IntegerField(default=0)),
                ('number_of_latest_success_attempt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScienceSubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_index', models.CharField(default='0', max_length=10)),
                ('topic_name', models.CharField(default='0', max_length=500)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('number_of_success_first_attempt', models.IntegerField(default=0)),
                ('number_of_latest_success_attempt', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='sciencetopic',
            name='question_model',
        ),
        migrations.RemoveField(
            model_name='sciencetopic',
            name='question_text',
        ),
        migrations.AddField(
            model_name='sciencetopic',
            name='topic_name',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
