# Generated by Django 3.1.7 on 2021-06-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0015_auto_20210628_0637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicReport',
        ),
        migrations.AddField(
            model_name='sciencelevel3topic',
            name='number_of_attempted_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sciencesubtopic',
            name='number_of_attempted_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sciencetopic',
            name='number_of_attempted_questions',
            field=models.IntegerField(default=0),
        ),
    ]
