# Generated by Django 3.1.7 on 2021-07-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0017_auto_20210628_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciencequestion',
            name='subtopic_number',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='sciencequestion',
            name='topic_number',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
