# Generated by Django 3.1.7 on 2021-08-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0018_auto_20210705_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencequestion',
            name='self_rated_score',
            field=models.IntegerField(default=-1),
        ),
    ]
