# Generated by Django 3.1.7 on 2021-08-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0019_sciencequestion_self_rated_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencequestion',
            name='answer_image_name',
            field=models.CharField(default='default_pic.png', max_length=200),
        ),
    ]
