# Generated by Django 3.1.7 on 2021-08-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0021_auto_20210808_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciencequestion',
            name='question_text',
            field=models.CharField(default='*', max_length=2000),
        ),
    ]
