# Generated by Django 3.1.7 on 2021-08-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0022_auto_20210808_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sciencequestion',
            old_name='self_rated_score',
            new_name='first_self_rated_score',
        ),
        migrations.AddField(
            model_name='sciencequestion',
            name='latest_self_rated_score',
            field=models.IntegerField(default=-1),
        ),
    ]
