# Generated by Django 3.1.7 on 2021-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0023_auto_20210808_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencelevel3topic',
            name='avg_first_self_rated_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sciencelevel3topic',
            name='avg_latest_self_rated_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sciencesubtopic',
            name='avg_first_self_rated_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sciencesubtopic',
            name='avg_latest_self_rated_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sciencetopic',
            name='avg_first_self_rated_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sciencetopic',
            name='avg_latest_self_rated_score',
            field=models.FloatField(default=0.0),
        ),
    ]
