# Generated by Django 3.1.7 on 2021-08-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0024_auto_20210808_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencelevel3topic',
            name='number_of_attempted_open_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sciencesubtopic',
            name='number_of_attempted_open_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sciencetopic',
            name='number_of_attempted_open_questions',
            field=models.IntegerField(default=0),
        ),
    ]
