# Generated by Django 4.0.4 on 2022-05-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0028_answerrecords_englishlevel3topic_englishquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerrecords',
            name='number_of_attempts',
        ),
        migrations.RemoveField(
            model_name='answerrecords',
            name='number_of_successful_attempts',
        ),
        migrations.RemoveField(
            model_name='answerrecords',
            name='success_on_first_attempt',
        ),
        migrations.AddField(
            model_name='answerrecords',
            name='mcq_answer_successful',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
