# Generated by Django 3.1.7 on 2021-04-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210418_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_model_index',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_model',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
