# Generated by Django 3.1.7 on 2021-06-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210418_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='attempted_answer',
            new_name='attempted_answer_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer',
            new_name='correct_answer_a',
        ),
        migrations.AddField(
            model_name='question',
            name='attempted_answer_b',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='attempted_answer_c',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_b',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_c',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
